image: Visual Studio 2017
version: b{build}-{branch}

clone_folder: c:\projects\gatorgrader

# clone using a zip file, not git
shallow_clone: true

platform:
  - x86
  - x64

matrix:
  fast_finish: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'

init:
  - set GATORGRADER_HOME "c:\projects\gatorgrader"
  - set PIPENV_VENV_IN_PROJECT 1
  - set PIPENV_IGNORE_VIRTUALENVS 1

install:
  - gem update --system
  - gem install mdl
  - cinst gradle
  - pip install pipenv
  - pipenv install --dev --skip-lock --python "$PYENV_VERSION"

build_script:
  - pipenv run cover
  - pipenv run lint --check

test: off
