image: Visual Studio 2017
version: b{build}-{branch}

clone_folder: c:\projects\gatorgrader

# clone using a zip file, not git
shallow_clone: true

environment:
  # SHELL expected by pipenv
  SHELL: 'windows'
  matrix:
    - PYTHON_VERSION: 3.7.3
    - PYTHON_VERSION: 3.6.8

cache:
  - '%LOCALAPPDATA%\pip\Cache'

init:
  - set GATORGRADER_HOME='c:\projects\gatorgrader'
  - set PIPENV_VENV_IN_PROJECT=1
  - set PIPENV_IGNORE_VIRTUALENVS=1
  - set PATH=c:\Ruby26\bin;c:\Python37;%PATH%

install:
  - gem install mdl
  - pip install pipenv
  - pipenv install --dev --skip-lock --python %PYTHON_VERSION%

before_build:
  - python --version
  - pipenv --version

build_script:
  - pipenv run cover-win
  - pipenv run lint-win --check

test: off
deploy: off
