[tool.poetry]
name = "gatorgrader"
version = "0.0.0"
description = "Automated Grading Tool that Checks the Work of Writers and Programmers"
authors = ["Gregory Kapfhammer <gkapfham@allegheny.edu>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/GatorEducator/gatorgrader"
repository = "https://github.com/GatorEducator/gatorgrader"
documentation = "https://github.com/GatorEducator/gatorgrader"
keywords = ["grading", "education", "allegheny"]
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Operating System :: OS Independent",
  "Environment :: Console",
  "Development Status :: 5 - Production/Stable",
  "Topic :: Education :: Testing",
  "Topic :: Utilities",
]
packages = [{ include = "gator" }, { include = "gatorgrader.py" }]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/GatorEducator/gatorgrader/issues"

[tool.poetry.scripts]
gatorgrader = "gatorgrader:main"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
GitPython = "^3.1.27"
requests = "^2.28.1"
commonmark = "^0.9.1"
num2words = "^0.5.10"
pluginbase = "^1.0.1"
pyyaml = ">=6.0.2"

[tool.poetry.dev-dependencies]
pylint = "^2.14.5"
black = "^22.6.0"
pytest = "^7.1.2"
codecov = "^2.1.13"
flake8 = "^4.0.1"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.5"
bandit = "^1.7.4"
pydocstyle = "^6.1.1"
radon = "^5.1.0"
xenon = "^0.9.0"
snoop = "^0.4.1"
taskipy = "^1.10.2"
toml = "^0.10.2"

[tool.taskipy.tasks]
test = "./scripts/test.sh"
cover = "./scripts/cover.sh"
lint = "./scripts/lint.sh"
test-win = 'scripts\\test.bat'
cover-win = 'scripts\\cover.bat'
lint-win = 'scripts\\lint.bat'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["gatorgrader"]
branch = true