name: Lint and Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6.12, 3.7]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install --dev --skip-lock --python ${{ matrix.python-version }}
      - name: Execute tests
        if: runner.os == 'Linux'
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test
      - name: Execute tests
        if: runner.os == 'Windows'
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test-win
