# Publishing workflow

name: Publish

# Use more columns for terminal output
env:
  COLUMNS: 120
  PYTHONIOENCODING: utf8
  
# trigger the publishing of the 
# gatorgrade package to PyPI
# with any tag starting with 'v'
on:
  push:
    tags:
      - 'v*'
      
# Create one single job
# that publishes the package
# to PyPI using Poetry

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          poetry install
      - name: Configure Poetry for PyPI
        run: |
          poetry config repositories.pypi https://upload.pypi.org/legacy/
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish package to PyPI
        run: |
          poetry publish --repository pypi --build
      - name: Check for Successful Publication
        run: |
          version=$(poetry version --short)
          echo "Checking if package gatorgrade version $version is available on PyPI..."
          response=$(curl -s "https://pypi.org/pypi/gatorgrade/$version/json")
          if echo "$response" | grep -q "$version"; then
            echo "Package gatorgrade version $version is successfully published on PyPI."
          else
            echo "Package gatorgrade version $version was not found on PyPI."
            exit 1
          fi
          